---
language: python
python:
  - 2.7
services:
  - docker
install:
  - docker build -t lighttpd .
  - docker run --name lighttpd -v /etc/localtime:/etc/localtime:ro -v $PWD/htdocs:/var/www/localhost/htdocs -p 8080:80 -p 443:443 -d lighttpd:latest
script:
  - docker ps | grep -q lighttpd
  - test "$(curl -I http://localhost:8080 2>/dev/null | head -n1 | cut -d' ' -f2)" == "200"
  - test "$(curl -I --insecure https://localhost 2>/dev/null | head -n1 | cut -d' ' -f2)" == "200"
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then
    docker build -t lighttpd .;
    docker tag lighttpd:latest m4rcu5/lighttpd:latest;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push m4rcu5/lighttpd:latest;
    fi
